### ISSUE TITLE
readme的图片好像挂了

### ISSUE THREAD

**Issue by easyworld** [AlanStar233/dodo-demo-Project#1]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/8280291/215301956-bc4b3178-e521-413d-8de6-bed0aa6d29a9.png">

**Comment by AlanStar233** [comment]
你好，文档内图片问题已在最新次提交 #[2f3085f](https://github.com/AlanStar233/dodo-demo-Project/commit/2f3085f2e7c5a3752c27b116a05747b40e5ab83f) 中修复，改用COS作为图床存储内容。 

后续也会将教程中的图片存储至图床中。
